minimumReleaseAge: 2880

onlyBuiltDependencies:
  - esbuild
  - gl
  - sharp
  - turbo

ignoredBuiltDependencies:
  - core-js

patchedDependencies:
  harfbuzzjs@0.10.0: patches/harfbuzzjs@0.10.0.patch

packages:
  - 'playground'
  - '.'
