blank_issues_enabled: false
contact_links:
  - name: Question & Ideas
    url: https://github.com/vercel/satori/discussions
    about: Ask questions and share your thoughts with other community members
